[OING-25] chore: NCP ObjectStorage 세팅
depromeet/14th-team5-BE pull request #16
Opened 2023-11-26 13:41 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
추후 개발할 기능들을 위해 이미지 업로드를 수행할 NCP ObjectStorage 세팅을 추가했습니다.

## ➕ 추가/변경된 기능

---
- NCP ObjectStorage 버킷 생성
- NCP ObjectStorage 관련 설정 세팅
- 파일 업로드 로직 구현
- 파일 업로드 테스트 코드 작성
  - 실제 bucket에 파일을 올리는 방식으로 테스트 코드를 구현하는 건 지양해야 하므로 `Mockito`를 이용하여 기능이 잘 수행되는 지 확인했습니다 

## 🥺 리뷰어에게 하고싶은 말

---
- Mock을 활용한 파일 업로드 테스트 코드를 작성하면서, `InfraTest`와 `FileMockingUtils`과 같은 테스트 환경과 관련된 파일들은 `test.java.com.oing.support` 패키지에 추가되었습니다. 그리고 실제 파일 업로드 테스트를 수행하는 코드는 `test.java.com.oing.config.support` 패키지에 위치하고 있습니다. 이러한 구조가 좋은 것인지 의문이 들어 다른 좋은 구성이 있다면 추천해주세요.

<img width="300" alt="image" src="https://github.com/depromeet/14th-team5-BE/assets/69844138/bff0b19f-ab95-44e8-a96a-eb9d3d8078b9">

## 🔗 참조 or 관련된 이슈

---
https://no5ing.atlassian.net/browse/OING-25

2023-11-26 13:53 UTC, CChuYong requested changes

2023-11-26 13:53 UTC, CChuYong commented on config/src/main/java/com/oing/config/properties/ObjectStorageProperties.java
https://github.com/depromeet/14th-team5-BE/blob/dev/config/src/main/java/com/oing/config/properties/WebProperties.java

처럼 바로 yaml을 오브젝트 형태로 바인딩할 수 있어요!

2023-11-26 13:53 UTC, CChuYong commented on config/src/main/java/com/oing/config/support/FileUploader.java
> +    public String uploadImage(MultipartFile multipartFile) {
백엔드에서 Multipart형태로 파일을 받으면 모든 파일 용량 트래픽까지 서버가 감당하게됩니다,,
그래서 보통은 Presigned-URL을 발급하고 프론트에서 직접 그 url에 업로드 하는 식으로 구성해요!
그리고 프론트가 처리 후에 URL을 백엔드로 넘겨주는 식으로 보통 이미지/파일 업로드를 처리하는것이 좋을 것 같아요!

2023-11-26 17:27 UTC, Ji-soo708 reviewed
test coverage가 실패한 이유 보니까 `dev`에 있는 Token 관련 코드가 제 브랜치에 없어서 발생한 거 같네요.

2023-11-26 17:27 UTC, Ji-soo708 commented on config/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
> +public class S3PreSignedUrlProvider {
PreSignedUrl 방식으로 변경했습니다.

2023-11-26 17:27 UTC, Ji-soo708 commented on config/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
> +    void getPreSignedUrl() {
스웨거때처럼 API 요청을 하면 Authentication failed가 떠서 일단 PresignedUrl 생성하는 메소드에 대해 테스트만 진행했습니다.

2023-11-26 17:28 UTC, Ji-soo708 commented on config/src/main/java/com/oing/config/support/FileUploader.java
> +    public String uploadImage(MultipartFile multipartFile) {
네 Presigned url 로 변경했습니다!

2023-11-27 01:54 UTC, CChuYong requested changes
수고하셨습니다!
큰 문제는 없는데 약간 다같이 논의가 필요한 부분이 있어서 우선 펜딩하였고
오늘 저녁 회의때 한번 공유하면 좋을 것 같습니다!

2023-11-27 01:54 UTC, CChuYong commented on config/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
config 모듈은 모든 모듈을 dependency로서 가지고 있지만, 다른 어떤 모듈도 콘피그 모듈을 참조하고 있지 않아서 이 클래스는 콘피그 모듈을 제외한 다른 모듈에서 접근할 수 없어요!

common 모듈에 이 Provider 관련 interface를 하나 선언해두시고, 그 구현체로 이 클래스에서 Implement 해두어야 다른 모듈들에서 interface를 타고 접근할 수 있을거에요!

2023-11-27 01:54 UTC, CChuYong commented on config/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
제가 dto 생성시 java17에서 나온 record를 주로 사용하는데,
이 안건 오늘 저녁에 한번 같이 공유해보면 좋을 것 같아요.

2023-11-27 01:54 UTC, CChuYong commented on config/src/main/resources/application.yaml
이거 아마 기본값 지정되어있지 않아서 배포 나가면 바로 터질 것 같아서
env 관련해서도 같이 한번 논의하면 좋을 것 같네요!

2023-11-27 02:55 UTC, Ji-soo708 commented on config/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
아 그러네요! 저번 지식공유 때 나왔던 얘기네요ㅎㅎ 반영하도록 하겠습니다

2023-12-02 08:15 UTC, merged