[OING-277] fix: test용 RedisConfig 추가
depromeet/14th-team5-BE pull request #198
Opened 2024-03-02 11:36 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
서버 이전을 하면서 레디스가 serverless(cluster mode)로 바뀌어 레디스 설정 파일에서는 클러스터 모드인데 임베디드 레디스는 단일 구성 설정이라 제대로 동작되지 않았습니다. 
클러스터 모드이지만 port를 하나만 쓰는 단일 구성형태라 임베디드 레디스는 그대로 두고 임베디드 레디스를 위한 테스트용 RedisConfig 파일을 생성했습니다.

## ➕ 추가/변경된 기능

---
- test용 RedisConfig 추가

## 🥺 리뷰어에게 하고싶은 말

---
임베디드 레디스가 실행되어 캘린더쪽 테스트코드가 돌아가는지 확인해주세요~

2024-03-03 09:32 UTC, CChuYong requested changes

2024-03-03 09:32 UTC, CChuYong commented on gateway/src/main/java/com/oing/config/RedisConfig.java
> +@Profile({"local", "dev", "prod"})
!test 로 하시면 될거같아요

2024-03-04 09:47 UTC, Ji-soo708 commented on gateway/src/main/java/com/oing/config/RedisConfig.java
> +@Profile({"local", "dev", "prod"})
넵 반영했습니다~

2024-03-04 11:57 UTC, CChuYong approved these changes

2024-03-04 11:57 UTC, merged