[OING-286] refactor: post 모듈 전체적으로 리팩터링
depromeet/14th-team5-BE pull request #206
Opened 2024-03-20 10:48 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
post 모듈 전체적으로 리팩터링했습니다.

## ➕ 추가/변경된 기능

---
- post 모듈의 회원리얼이모지/리액션/코멘트 관련 안티패턴 리팩터링
- post 모듈의 엔티티에서 공통적인 MemberPost 제거

## 🥺 리뷰어에게 하고싶은 말

---
기본적인 기능 호출해서 문제 없는 거 같아 PR 올렸는데 추가적으로 수정되어야 하는 부분 있으면 알려주세요

2024-03-22 12:30 UTC, Kwon770 requested changes
코멘트 단 부분확인 부탁드려요.

그런데 다음부터는 PR 분리해서 부탁드려요 😂 중간까지 확인했는데, 리뷰라고 할 수가 없는 양이에요... 일단은 코멘트한 부분을 위주로 전체적으로 점검 부탁드려요!

2024-03-22 12:30 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
>          if (!postFamilyId.equals(loginFamilyId)) {
다른 모듈이나 메소드와 일관성있게, validate함수로 빼서 검증하는게 좋울 것 같아요

2024-03-22 12:30 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
>          String postImgKey = preSignedUrlGenerator.extractImageKey(request.imageUrl());
Post의 save 비즈니스 코드가 Controller에 아직 있어요.😵 혹시 이유가 있어 의도한걸까요??

2024-03-22 12:30 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/ReactionController.java
> +        Post post = postService.findMemberPostById(postId);
@CChuYong 흠.. @Transactional 태그 제외하고, 이런 aggregation 코드 어떻게 생각하세요? 애매하네요.

2024-03-22 12:39 UTC, CChuYong commented on post/src/main/java/com/oing/controller/ReactionController.java
> +        Post post = postService.findMemberPostById(postId);
사실 전 아래 createPostReaction 첫번째 파라미터가 postId여도 될거같습니다

2024-03-22 13:02 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
>          String postImgKey = preSignedUrlGenerator.extractImageKey(request.imageUrl());
post도메인의 안티패턴 로직 개선은 이전PR에서 진행중입니다!

2024-03-23 10:00 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/CommentController.java
> +public class CommentController implements CommentApi {
@transactional은 제가 빠뜨린 게 맞아서 고쳐야 하고 비즈니스 로직은 서비스로 다 옮긴 거 맡습니다!

2024-03-23 10:01 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/MemberRealEmojiController.java
>      @Transactional
넵 체크 감사합니다~

2024-03-23 10:13 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
>          if (!postFamilyId.equals(loginFamilyId)) {
넵 좋습니다~

2024-03-23 10:23 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/ReactionController.java
> +        Post post = postService.findMemberPostById(postId);
aggregation한 이유는 ReactionService에서 Post를 찾을 수 없어 PostService의 메서드를 쓰기 위해 위처럼 리팩터링했습니다. ReactionService에서 다른 서비스 메서드를 호출해도 되나요??

2024-03-23 15:36 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/ReactionController.java
> +        Post post = postService.findMemberPostById(postId);
전 영민님과 같은 의견이긴한데, 제가 아는바로는 가장 간단한 구조 상으로 XXXController가 XXXService를 부르고, XXXService가 YYYService ZZZService를 부르는 방식이였어요. 특히 우리는 모듈까지 분리했으니 Bridge가 아니고 같은 모듈이라면 다른 서비스를 부르는게 문제가 없다고 생각해요.

저의 다른 리뷰의 연장선상으로 비즈니스 코드와 Transcational 등을 통한 트랜잭션 관리를 Service가 하도록 수정하고 있다보니, Service 메소드와 상관없는 코드를 aggregation해야해서 Service에서 파급효과 취급이거나(극단적인 ex. createPost와 increasePostScore) Bridge가 필요하지 않다면 저는 이러한 코드들을 Service로 응집시켜요. Controller는 전혀 다른 속성의 코드들을 aggregation하거나, API/Controller 적인 동작, 불가피한 Bridge 사용(MSA라면 다른 서버에 call하는 느낌으로)에만 사용해요.

지수님이 이런 느낌으로 구성하는데 분명한 근거가 있다면 표현만 해주시면 머지 되는 것에 존중합니다!

2024-03-23 15:37 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
>          String postImgKey = preSignedUrlGenerator.extractImageKey(request.imageUrl());
아 그럼 머지전에 pull하고 처리하시는거죠? 알겠습니다!

2024-03-25 14:43 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
>          String postImgKey = preSignedUrlGenerator.extractImageKey(request.imageUrl());
넵 conflicts 다 해결했습니다~

2024-03-25 15:16 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/ReactionController.java
> +        Post post = postService.findMemberPostById(postId);
오늘 서버 회의를 통해 다음을 따르기로 했습니다!같은 모듈 내에 위치한 서비스라 하더라도, 서로 다른 도메인 서비스임을 감안하여, Controller에서 필요한 경우 서로 다른 도메인 서비스를 통합하는 방식으로 진행

2024-03-25 15:19 UTC, Kwon770 approved these changes
수고하셨어요! 승인합니다.

다만 리팩토링 양이 방대하니, 개발서버에서 테스트 진행합시다!

2024-03-25 15:20 UTC, merged