refactor: Member 모듈의 안티패턴과 짜잘한 부분 리팩토링
depromeet/14th-team5-BE pull request #210
Opened 2024-03-20 14:29 UTC by Kwon770

## ❓ 기능 추가 배경

---
전체 모듈 리팩토링 및 안티패턴 개선 주간 중 Member 모듈 리팩토링에 대한 PR입니다. 전체적으로 수정하였고, 안티패턴 이외의 부분은 스타일일수도 있기 때문에, 슬랙에서도 논의하겠지만 코드에서도 자유롭게 피드백해주세요.

## ➕ 추가/변경된 기능

---
- 모듈 전체에서 네이밍 컨벤션에 맞지않은 메소드, 변수명 수정
- 가독성 좋게 모듈 전체 포멧팅 수정
- Update, Delete transaction이 Controller에 노출된 안티패턴을 수정
- 사용하지 않지만 ParameterResolver로 파싱하고 있는 파라미터들 제거
- validate 함수를 더 적합한 위치로 옮기고, 이름 수정
- 던지고 있는 예외를 더 명확한 예외 클래스와 에러 메시지로 수정

## 🥺 리뷰어에게 하고싶은 말

---
슬랙에서도 논의하겠지만 코드에서도 자유롭게 피드백해주세요.

2024-03-20 14:31 UTC, Kwon770 commented
code smell로 인한 SonarCloud B판정은 사소한 이슈라 무시하고 리뷰 일단 해주세요~

2024-03-20 15:38 UTC, Ji-soo708 requested changes
쭉 보다가 validate 관련해서 코멘트 남겼습니다. 확인해주세요~

2024-03-20 15:38 UTC, Ji-soo708 commented on member/src/main/java/com/oing/controller/MemberController.java
> +        validateMemberIdMatch(memberId, loginMemberId);
저번 오프 회의때 post 모듈 리팩터링하면서 영민님한테 validateMember 같은 유효성 검증 로직은 컨트롤러에 있는 게 맞는지 서비스에 있는 게 맞는지 여쭤봤는데 영민님이 이런 검증도 원래는 서비스에 있는 게 맞다고 하셨어요! 그래서 제가 진행한 리팩터링 중 save/update/delete에 대해서는 멤버 검증 로직도 서비스에 넣어서 진행했습니다. validateMemberIdMatch도 서비스로 옮기는 게 맞다고 생각합니다.

2024-03-22 12:53 UTC, Kwon770 commented on member/src/main/java/com/oing/controller/MemberController.java
> +        validateMemberIdMatch(memberId, loginMemberId);
그땐 Member name length였나 도메인 속성 관련된 로직에 관한 이야기였던 것 같은데, 이번 리팩토링하면서 다시 생각해보니 이게 더 맞다고 생각해서 일단 진행했어요.

Service로 옮기는게 더 맞다고 생각하는 이유가 뭘까요? 요번 PR에서 제 판단 기준은
- Controller에서 담당하는 것에 대한 검증은 Controller에서 진행한다.
Controller가 받아온 parmater와 ParameterResolver가 받아온 loginMemberId의 매칭여부를 검증하는 것이니까, Controller에서 검증하는게 맞다고 생각해요. 그 이유는
    1. 검증의 대상이 되는 것이 모두 Controller에서 생성되었으니, 그 검증 책임도 Controller에 있다고 생각해요. (책임 분리)
    2. 1의 연장선상으로 Serevice에 있는 validate를 다룰 때 Controller도 왔다갔다해야 해요. (결합성)

- Domain 속성에 대한 검증은 도메인에서 한다.
예를들어, Post content가 1~8자여야한다는 검증이라면 Post Entity 속에서 해야한다고 생각해요. 그 이유는 위의 두 가지와 같은데, 짧게 언급하자면
      1. Post entity의 속성에 의해 검증하는 내용이니까, 당연히 validate 코드가 Post entity에 있어야 한다고 생각해요.
      2. 1 ~ 8 자라는 검증의 기준이 되는 정보가 Entity column definition이 기준이니까, 컬럼 선언와 같은 공간에 validate가 있어야 한다고 생각해요.

2024-03-25 14:56 UTC, CChuYong commented on member/src/main/java/com/oing/controller/MemberController.java
> +        validateMemberIdMatch(memberId, loginMemberId);
- 들어온 요청에 대한 검증은 Controller에 있는게 맞을 것 같습니다
- 실제 비즈니스 로직에 모든 경우(?)에 필요한 검증은 서비스 내에 있는게 맞을 것 같습니다

2024-03-31 04:09 UTC, Ji-soo708 commented on member/src/main/java/com/oing/controller/MemberController.java
> +        validateMemberIdMatch(memberId, loginMemberId);
회의에서 검증로직까지 Service에서 다 처라하기로 결정함

2024-03-31 04:10 UTC, Ji-soo708 approved these changes
검증로직 서비스에서 다 처리하기로 해서 승인합니다

2024-04-02 13:55 UTC, closed without merging