[OING-302] feature: 미션 포스트 작성/조회 모킹 API 추가
depromeet/14th-team5-BE pull request #228
Opened 2024-04-11 09:20 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
미션 포스트 작성/조회 모킹 API 추가했습니다.

## ➕ 추가/변경된 기능

---
- 미션 포스트 작성/조회 모킹 API 추가

## 🥺 리뷰어에게 하고싶은 말

---
기존 포스트 작성/조회 API에 param을 추가해서 미션 포스트도 처리 가능하도록 설계했습니다. 더 좋은 의견이 있다면 알려주세요~
(param이 없거나 feed -> feed post / mission -> mission post)

🚨 포스트 조회의 경우, QueryDSL로 페이지네이션을 처리하고 있는데 임의적으로 응답을 모킹하기가 힘들어 일단 **?type=mission 으로 조회해도 기존에 있던 feed type의 포스트가 조회**되도록 했습니다. 임의로 응답 모킹이 가능한데 그 방법으로 처리하길 원하신다면 그렇게 바꾸겠습니다!

2024-04-13 07:42 UTC, Kwon770 requested changes
확인 부탁드려요!

2024-04-13 07:42 UTC, Kwon770 commented on post/src/main/java/com/oing/restapi/PostApi.java
> +            String type,
RequestParam 매게변수 타입도 enum으로 하면, 스프링이 기본적으로 제공하는 StringToEnum static 컨버터 클래스가 변환해줍니다! 또한 Swagger에서 Enum 목록에 있는 string을 보여줄 수 있고, Enum에 없는 string이 들어오면 MethodArgumentTypeMismatchException 예외를 핸들링할 수 있습니다!

2024-04-13 07:42 UTC, Kwon770 commented on post/src/main/java/com/oing/service/PostService.java
> +    public Post createMissionPost(CreatePostRequest request, String loginMemberId, String loginFamilyId) {
트랜잭션 어노테이션이 빠진 것 같아요!

2024-04-13 07:45 UTC, Kwon770 commented
#225 에 해당하는 부분이지만, 본 PR과 연관되어 추가 리뷰남깁니다!

Post모듈의 Type Enum에서 기존 생존신고 게시글을 "FEED"로 구분하였는데, 정확히는 FEED가 게시글들의 목록에 대한 의미로 받아들여지는 것 같아요. 이보다는 기획/디자인에서 지칭하는 "생존신고"라는 의미가 담겨서, 미션 게시글과 구분이 되면 좋을 것 같다고 생각해요.

Report(생존"신고")는 경찰에 "신고"와 같은 신고의 의미가 강한 것 같아 적합하지 않고, "생존"신고의 명사형인 Survival은 어떻게 제안드려요!

2024-04-15 08:27 UTC, Ji-soo708 commented on post/src/main/java/com/oing/restapi/PostApi.java
> +            String type,
오 넵 좋습니다! 그렇게 수정하겠습니다.

2024-04-15 08:31 UTC, Ji-soo708 commented on post/src/main/java/com/oing/service/PostService.java
> +    public Post createMissionPost(CreatePostRequest request, String loginMemberId, String loginFamilyId) {
createMemberPost에서 분기 쳐서 createFeedPost와 createMissionPost를 수행하고 있어서 createMemberPost에만 트랜잭션을 적용했습니다!

2024-04-15 08:35 UTC, Ji-soo708 commented
> #225 에 해당하는 부분이지만, 본 PR과 연관되어 추가 리뷰남깁니다!
> 
> Post모듈의 Type Enum에서 기존 생존신고 게시글을 "FEED"로 구분하였는데, 정확히는 FEED가 게시글들의 목록에 대한 의미로 받아들여지는 것 같아요. 이보다는 기획/디자인에서 지칭하는 "생존신고"라는 의미가 담겨서, 미션 게시글과 구분이 되면 좋을 것 같다고 생각해요.
> 
> Report(생존"신고")는 경찰에 "신고"와 같은 신고의 의미가 강한 것 같아 적합하지 않고, "생존"신고의 명사형인 Survival은 어떻게 제안드려요!

넵 좋습니다. 생각해보니 FEED라는 단어가 갖는 의미가 모호해서 더 명확한 SURVIVAL로 수정하겠습니다!

2024-04-15 09:59 UTC, CChuYong commented on post/src/main/java/com/oing/domain/Type.java
>      public static Type fromString(String typeKey) {
Type보단 PostType이 의미상 정확할 것 같슴다! (나중에 PostComment에도 타입이 생긴다거나.. 하는 경우..??)

2024-04-15 09:59 UTC, CChuYong commented on post/src/main/java/com/oing/restapi/PostApi.java
> +            @Parameter(description = "게시물 타입", example = "SURVIVAL")
기존 API (아에 type이란 쿼리파람 없이 조회하는 경우) 에도 문제 없이 작동하는지 더블체크 한번씩만 부탁드립니다!

2024-04-15 09:59 UTC, CChuYong commented on post/src/main/java/com/oing/service/PostService.java
> +        if (type.equals(Type.SURVIVAL)) {
switch return 형태로 만들면 더 깔끔할 것 같아요

2024-04-15 10:29 UTC, Ji-soo708 commented on post/src/main/java/com/oing/restapi/PostApi.java
> +            @Parameter(description = "게시물 타입", example = "SURVIVAL")
문제 없이 동작되는 거 확인하고 올렸습니다!

2024-04-15 10:31 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/Type.java
>      public static Type fromString(String typeKey) {
넵 좋습니다. Post Entity에서 type 필드명은 따로 바꾸지 않겠습니다! postType이 필드명이면 중복 느낌이 강하네요

2024-04-15 10:57 UTC, Ji-soo708 commented on post/src/main/java/com/oing/service/PostService.java
> +        if (type.equals(Type.SURVIVAL)) {
오 좋습니다! 고치면서 생각해보니 순찬님 피드백 받아서 파라미터 타입을 이넘으로 처리했는데 따로 예외처리할 필요도 없었네요.

2024-04-15 12:37 UTC, Kwon770 approved these changes
수고하셨습니다!! LGTM

2024-04-15 12:37 UTC, merged