feat: Mission 모듈 추가
depromeet/14th-team5-BE pull request #230
Opened 2024-04-15 15:22 UTC by Kwon770

## ❓ 기능 추가 배경

---
미션과 일일 미션 이력 엔티티를 포함한 Mission 모듈을 추가했습니다.

## ➕ 추가/변경된 기능

---
- Mission, DailyMissionHistory 엔티티 추가
- 추가된 엔티티에 대한 flyway db.migration file 추가
- Mission의 기본적인 CRUD 메소드 추가
- DailyMissionHistory의 기본적인 CR 메소드 추가

## 🥺 리뷰어에게 하고싶은 말

---

@Ji-soo708  이미 회의에서 논의된 내용들이고 간단한 코드들이라 바로 리뷰머지해주시면, 빠른 시일 내에 프론트/백엔드 모두 미션과 관련된 기능을 개발할 수 있도록, API와 **Service 메소드**를 모킹하도록 하겠습니다.

2024-04-15 15:45 UTC, Ji-soo708 requested changes
작업량 많으셨을 텐데 수고하셨습니다! save 메서드에서 두 번 저장하는 문제가 보여 코멘트 남겼습니다~

2024-04-15 15:45 UTC, Ji-soo708 commented on mission/src/main/java/com/oing/service/MissionService.java
> +        return MissionResponse.from(missionRepository.save(mission));
missionRepository에 두 번 save하고 있습니다!

2024-04-15 15:45 UTC, Ji-soo708 commented on mission/src/main/java/com/oing/service/DailyMissionHistoryService.java
> +        return DailyMissionHistoryResponse.from(dailyMissionHistoryRepository.save(dailyMissionHistory));
여기도 dailyMissionHistory를 두번 save하고 있습니다!

2024-04-15 17:34 UTC, Ji-soo708 reviewed
그리고 갑자기 .DS_Store 파일이 생겼네요..? 이부분도 삭제 부탁드립니다!

2024-04-15 23:27 UTC, Kwon770 commented on mission/src/main/java/com/oing/service/MissionService.java
> +        return MissionResponse.from(missionRepository.save(mission));
앗.. command + z를 이상하게 했네요..

2024-04-15 23:27 UTC, Kwon770 commented on mission/src/main/java/com/oing/service/DailyMissionHistoryService.java
> +        return DailyMissionHistoryResponse.from(dailyMissionHistoryRepository.save(dailyMissionHistory));
앗.. command + z를 이상하게 했네요..

2024-04-16 01:31 UTC, Ji-soo708 approved these changes
수고하셨습니다!

2024-04-16 01:48 UTC, merged