[OING-315] feature: 미션 게시글 업로드/조회 API 구현 (검증 로직 제외)
depromeet/14th-team5-BE pull request #236
Opened 2024-04-17 14:46 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
미션 게시글 업로드/조회 API를 구현했습니다. (해당 회원이 이미 미션 글을 작성한 적이 있는지와 같은 기본적인 검증 로직은 있지만 해당 회원이 미션 게시글 기능에 접근할 권한이 있는지에 대한 검증 로직은 프론트 편의성을 위해 제외했습니다. 다음주 중으로 추가하게 될 거 같습니다.)

## ➕ 추가/변경된 기능

---
- 미션 게시글 업로드 (검증 로직 제외)
  - 미션 기능 권한 조작하는 available 파라미터 추가
- 미션 게시글 조회 API 구현 (검증 로직 제외)
  - 미션 기능 권한 조작하는 available 파라미터 추가

## 🥺 리뷰어에게 하고싶은 말

---
기존에 있던 API를 수정한 거기도 하고 아직 검증 로직은 제외된 API라 해당 PR에서는 테스트 코드는 작성 안했지만 실제 API 호출 테스트 했을 때 문제 없이 잘 동작함을 확인했습니다.

2024-04-17 14:56 UTC, Ji-soo708 commented
Quality Gate가 Fail되는데 원인이 TODO 주석때문이라 무시해주세요~

2024-04-20 12:21 UTC, Kwon770 requested changes
미션 권한 검증 부분 체크 부탁드려요!

2024-04-20 12:21 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +        }
createdPost()와 fetchDailyFeeds() 모두 같은 검증 함수를 사용하고 있는데, validateMissionPostAccessMember()가 이 멤버가 미션을 업로드할 조건이 충족되었는지를 검증하는 것이 맞을까요? 그렇다면 가족의 과반수 이상이 생존신고를 했다면 구성원 모두 미션탭에 접근하여 다른 가족의 미션을 볼 수 있고, 미션을 업로드할 때만 각 구성원을 검증해야하는 것으로 알고있습니다.

2024-04-20 12:21 UTC, Kwon770 commented on post/src/main/java/com/oing/service/PostService.java
> +        validateUserHasNotCreatedPostToday(loginMemberId, loginFamilyId, PostType.MISSION, uploadTime);
검증 로직이니까, 검증하는 대상의 느낌을 더 주기 위해 Create 보단 Upload는 어떨까요?

2024-04-21 05:47 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
> +        }
네 맞습니다. 아직 모킹단계라 프론트에서 해당 기능에 대한 권한을 조작할 수 있도록 만든 임시 함수인데 차라리 모킹 단계에서부터 두 개의 검증 함수로 나누는 게 나중에 구현할 때 안헷갈리겠네요. 수정하겠습니다~ 👍

2024-04-21 06:10 UTC, Ji-soo708 commented on post/src/main/java/com/oing/service/PostService.java
> +        validateUserHasNotCreatedPostToday(loginMemberId, loginFamilyId, PostType.MISSION, uploadTime);
서버 로직에서 생각하면 사용자가 게시글을 올린다는 건 Post 객체를 생성하는 거니까 오히려 create 단어를 사용하는 게 더 적절하다고 생각합니다! upload 단어는 찾아보니까 파일을 업로드한다는 의미가 강하더라고요. 아니면 순찬님이 생각하시기에 upload가 더 적절하다는 이유가 따로 있을까요?? 항상 느끼지만 변수명이나 함수명 정하는 게 제일 어렵네요. 😂

2024-04-21 06:50 UTC, Kwon770 commented on post/src/main/java/com/oing/service/PostService.java
> +        validateUserHasNotCreatedPostToday(loginMemberId, loginFamilyId, PostType.MISSION, uploadTime);
음..! 단어를 읽었을때 느낌이 다르다고 생각해서였어요. 이 맥락에서 게시글이 생성되었다는 의미보다 유저가 업로드를 했는지가 더 중요한 의미라고 생각했는데, create는 유저가 생성했거나 서버가 생성했다로 2가지로 쓰일 수 있지만 upload는 당연히 유저가 업로드했다는 의미로만 해석된다고 생각했어요. 사실 정답이 없는 부분이기도 하고 스타일의 차이같기도 하네요. 아예 동사형으로 짓기도 했구요. 수정해야할 사안은 아닌 것 같으니, 승인하겠습니다! 🫡

2024-04-21 06:50 UTC, Kwon770 approved these changes
수고하셨어요!

2024-04-21 06:51 UTC, merged