[OING-329] refactor: 미션 검증 로직 중, 가족 구성원 수를 어제 날짜 기준으로 세도록 수정
depromeet/14th-team5-BE pull request #248
Opened 2024-05-02 15:32 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
오늘 날짜 기준으로 가족 구성원 수를 계산하는 기존 미션 키 관련 검증 로직이 문제가 될 수 있어, 가족 구성원 수를 어제 날짜 기준으로 세도록 수정했습니다.

## ➕ 추가/변경된 기능

---
- 미션 검증 로직 중, 가족 구성원 수를 어제 날짜 기준으로 세도록 수정

## 🥺 리뷰어에게 하고싶은 말

---
추가적으로 수정해야 할 부분이 있다면 알려주세요~

2024-05-05 08:01 UTC, Kwon770 requested changes
확인 부탁드려요~

2024-05-06 08:22 UTC, Ji-soo708 commented on gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
>      }
오 코드를 보니 isCreatedSurvivalPostByMajority 기능을 기존에 있던 method들로 구현이 가능하네요! 반영했습니다~

2024-05-06 14:45 UTC, Kwon770 approved these changes

2024-05-06 14:46 UTC, Kwon770 commented
수정된 내용 확인했습니다. LGTM!

2024-05-06 14:46 UTC, merged