refactor: 가족 이름 컬럼 타입 및 검증 로직 수정
depromeet/14th-team5-BE pull request #267
Opened 2024-06-26 08:38 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
`family_name` 컬럼을 아홉자까지 허용하도록 수정하고 `familyName`을 초기화해도 수정자가 기록되도록 수정했습니다.

## ➕ 추가/변경된 기능

---
- `family_name` 컬럼을 아홉자까지 허용
- `familyName`을 초기화해도 수정자가 기록되도록 수정

## 🥺 리뷰어에게 하고싶은 말

---
확인해주세요~

2024-06-26 08:39 UTC, Ji-soo708 commented on family/src/main/java/com/oing/domain/Family.java
> +        if ((familyName.codePoints().count() > 9) || familyName.isBlank()) {
회원 닉네임 로직처럼 사용자가 띄어쓰기 하나만 입력하면 예외던지도록 유지했습니다

2024-06-26 14:12 UTC, Kwon770 requested changes
전체적으로 문제없는데, 머지된 코드 중에 잘못된 변수명이 있어서 이것만 확인부탁드려요

2024-06-26 14:12 UTC, Kwon770 commented on family/src/main/java/com/oing/domain/Family.java
>      public void updateFamilyName(String familyName, String loginFamilyId) {
변수명이 잘못된 것 같아요. 기능상 수정 멤버 id가 들어가야하고 Service에서도 loginMemberId를 넣고있네요. 확인부탁드려요!

https://github.com/depromeet/14th-team5-BE/blob/5234e8e5d9a7e2266ccc22b2278962f6d8493a8a/family/src/main/java/com/oing/service/FamilyService.java#L64

2024-06-27 07:20 UTC, Ji-soo708 commented on family/src/main/java/com/oing/domain/Family.java
>      public void updateFamilyName(String familyName, String loginFamilyId) {
아 그러네요! 확인 감사합니다. 👍

2024-06-27 07:54 UTC, Kwon770 approved these changes
LGTM!

2024-06-27 07:54 UTC, merged