[OING-378] feat: 음성 댓글 관련 CRD API 구현
depromeet/14th-team5-BE pull request #278
Opened 2024-12-10 09:11 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
음성 댓글 CRD API 구현했습니다

## ➕ 추가/변경된 기능

---
- VoiceComment 엔티티 생성
- 음성 댓글 생성/삭제 API 구현
- 댓글 전체 조회 로직 수정
- 음성 댓글이 추가되면서 고려해야 할 로직들에 대해 수정

## 🥺 리뷰어에게 하고싶은 말

---
추가적으로 더 고려해야 할 점에 대해 코멘트 주세요~

## 🔗 참조 or 관련된 이슈

---
https://no5ing.atlassian.net/browse/OING-378

2024-12-10 09:15 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/CommentController.java
> +        List<PostCommentResponseV2> paginatedComments = combinedComments.subList(start, end);
음성 댓글이 추가되면서 기존 댓글 조회 API에서 각각 Comment와 VoiceComment에서 댓글 리스트 뽑아오고 합쳐서 정렬하고 페이지네이션 처리를 하고 있습니다. 그래서 기존 로직에 비해 복잡해졌습니다. 일단 성능에 문제가 생길 정도로 댓글이 많이 달리지는 않아서 이렇게 구현했는데 더 좋은 방법이 있다면 알려주세요~

2024-12-12 13:55 UTC, Ji-soo708 commented
테스트 에러가 뜨는데 그건 앞서 머지된 알림 pr에서 생긴 에러입니다..! 제 코드에 머지 코드가 반영돼있지 않아서 지금 당장은 해결할 수 없고 나중에 머지된 후 해결하거나 풀해서 해결해야 할 거 같아요

2024-12-14 10:09 UTC, Kwon770 requested changes
꽤 큰 PR이라 여러 제안을 남겨봤는데, 검토 부탁드려요..! 필수 수정 사항도 있어서 Request changes 남깁니다 😭

2024-12-14 10:09 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/CommentController.java
>      @Transactional
단순 조회이지만, 댓글이 다양해지면서 여러 쿼리를 실행해야하고 자바 코드 단의 로직도 많아져 실행시간이 길어질 수도 있을 것 같아요. 하지만 서비스 단위로 명시적 트랜잭션을 유지할 경우, 불필요하게 DB Connetion을 점유하게 될 것으로 보여요. 따라서 여기선 명시적 트랜잭션을 제거하는게 옳다고 저는 생각합니다!

2024-12-14 10:37 UTC, Ji-soo708 commented on common/src/main/java/com/oing/util/Paginator.java
> +        int totalPages = (int) Math.ceil((double) totalItems / pageSize);
그 부분을 놓쳤네요. 0이하는 잘못된 값이니까 예외를 반환하도록 하겠습니다!

2024-12-14 11:10 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/VoiceComment.java
> +@Entity(name = "voice_comment")
그 부분에 대해 커밋 추가했습니다!

2024-12-14 11:12 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/VoiceComment.java
> +public class VoiceComment extends BaseAuditEntity {
중간에 추상클래스를 둔다면 확실히 기존 코드보다 더 깔끔하고 가독성도 좋아질 거 같습니다! 좋은 의견인데 작업 시간이 좀 걸릴 거 같아 추후에 따로 PR을 올려 리팩토링하겠습니다. 👍

2024-12-14 11:48 UTC, Kwon770 reviewed
피드백 반영한 수정 확인 완료했습니다. 추상화와 관련된 부분을 제외하고는 전부 문제 없습니다!

추상화와 관련된 내용은 다음주 화요일 서버 회의때 논의해보고 추후 방향을 재논의하기 위해, 우선 Approve는 보류하겠습니다!

2024-12-14 11:48 UTC, Kwon770 commented on common/src/main/java/com/oing/util/Paginator.java
> +        int totalPages = (int) Math.ceil((double) totalItems / pageSize);
아 제가 놓쳤네요! 확인 감사합니다!

2024-12-22 15:27 UTC, Kwon770 approved these changes
이미 충분히 논의된 PR이라 Approve합니다! 추가 논의한 사항에 대해서는 별도의 PR을 만드는 것이 적절하다고 판단해 머지하겠습니다. 수고하셨습니다!

2024-12-22 15:27 UTC, merged