[OING-67] feat: 피드 업로드 API 모킹
depromeet/14th-team5-BE pull request #36
Opened 2023-12-13 09:53 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
피드 업로드 API 모킹 및 피드 업로드를 위한 presigned-url 요청 로직을 리팩터링했습니다.

## ➕ 추가/변경된 기능

---
- Post 도메인 ddl 및 엔티티 수정
  - `content` 컬럼 추가
  - `imageUrl` 컬럼 not null 설정 추가
- Post reaction 도메인 ddl 및 엔티티 수정
  - `ascii` 필드명을 `emoji`로 수정
- 피드 업로드 API 모킹
- 피드 업로드를 위한 presigned-url 요청 로직 리팩터링
  - 경로 수정: `/images/{memberId}` =>  `/images/feed`

## 🥺 리뷰어에게 하고싶은 말

---
추가적으로 수정해야할 부분이 있는지 확인해주세요. 🙂

2023-12-14 03:54 UTC, Kwon770 requested changes
모킹 작업이라 어디까지 리뷰해야할지 애매해서 일단 수정사항에 있는 내용 전체적으로 검토해봤습니다!

2023-12-14 03:54 UTC, Kwon770 commented on gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
> +        return UUID.randomUUID() + "_" + imageName;
특별한 의미없이 이름 중복 방지를 위해 randomUUID()를 쓰는 것이라면 ULID를 쓰는 것은 어떨까요? 저희 식별자에도 UUID가 아닌 ULID를 쓰고 있는데, 여러 장점이 있고 대시바 특수문자를 쓰지않는 점이 url에 쓰기 적합합니다. https://ssdragon.tistory.com/m/162

2023-12-14 03:54 UTC, Kwon770 commented on gateway/src/main/resources/db/migration/V2__modify_Post.sql
> +ALTER TABLE `member_post` ADD COLUMN `content` VARCHAR(8) NOT NULL;
기획상 게시글 텍스트는 필수 아니에용

2023-12-14 03:54 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +                request.content()
전달받은 requestBody를 한 번더 생성하는 이유가 무엇일까요?

2023-12-14 03:54 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +                    0, Collections.EMPTY_LIST, Collections.EMPTY_LIST));
지난 회의 때 제가 질문한건데 생성자에 필요없는 리스트 컬럼은 제거하고 생성자를 사용하기로 해서 수정부탁드려요 🥺

2023-12-14 03:54 UTC, Kwon770 commented on post/src/main/java/com/oing/domain/model/MemberPostReaction.java
> +    private String emoji;
Enum이 아니라 String이네요. 차후에 이모지를 사용자가 추가할 수 있다는 기획을 고려했기 때문일까요?

2023-12-14 03:54 UTC, Kwon770 commented on post/src/main/java/com/oing/domain/model/MemberPost.java
> +    @Column(name = "content")
저희 게시글 내용이 글자수 제한이 있는데, 확장성을 위해 컬럼단에서 제한하진 말고 코드로 validate하는게 좋을 것 같아요!

2023-12-14 05:57 UTC, CChuYong commented on gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
> +        return UUID.randomUUID() + "_" + imageName;
저도 동의합니다 IdentityGenerator 땡겨오셔서 집어넣으시면 ULID 생성할 수 있습니다!

2023-12-14 06:00 UTC, CChuYong approved these changes

2023-12-14 06:00 UTC, CChuYong commented on gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
> +        return UUID.randomUUID() + "_" + imageName;
추가적으로, 함수 명 uniqueImageName보다 동사 포함해서 generateUniqueImageName 같은게 좋을 것 같아요!
그리고 ImageName이 보존되어야할 필요는 없을 것 같아요 그냥 랜덤 경로여도 될 것 같습니다!

2023-12-14 09:22 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
> +                    0, Collections.EMPTY_LIST, Collections.EMPTY_LIST));
`Collections.EMPTY_LIST, Collections.EMPTY_LIST` 이 부분이 포함되지 않는 생성자를 하나 새로 선언해서 사용했으면 좋겠다는 말씀이시죠?

2023-12-14 09:24 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/model/MemberPostReaction.java
> +    private String emoji;
아 저 부분 제가 놓친 게 맞습니다. 그런데 추후에 이모지를 사용자가 추가한다는 기획을 고려하면 Enum보단 String으로 두는 게 더 나을 거 같기도 한데 어떤 방식이 나을까요? @Kwon770 @CChuYong

2023-12-14 09:29 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
> +                request.content()
제가 api 모킹 개념을 잘못 이해해서 저렇게 새로 선언했네요. 다시 바꿨습니다! 알려주셔서 감사합니다~

2023-12-14 09:30 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/model/MemberPost.java
> +    @Column(name = "content")
아하 넵. 코드에서 명시적으로 표시해주는 게 더 좋아보여서 그렇게 수정하겠습니다!

2023-12-14 09:50 UTC, Ji-soo708 commented on gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
> +        return UUID.randomUUID() + "_" + imageName;
이미지 확장자를 저장하기 위해 imageName까지 저장하도록 처리한건데 혹시 모를 보안성을 위해 확장자만 따로 추출해서 저장하도록 수정하겠습니다!

2023-12-14 10:05 UTC, Ji-soo708 reviewed
순찬님과 영민님이 남겨주신 코멘트 보고 전체적으로 수정했습니다. 1차 MVP때는 이모지 5개만 사용하지만 2차 MVP때 사용자 지정 이모지를 추가한다고 했는데 이 부분을 생각하면 이모지 타입을 Enum으로 선언하는 게 좋은 방법일지를 모르겠어서 의견 남겨주시면 감사합니다! 저는 아래 방법으로 처리가 가능하다면 Enum으로 해도 좋다고 생각합니다.

```
public enum Emoji {
    SMILE("smile"),
    HEART("heart"),
    STAR("star"),
    THUMBS_UP("thumbs_up"),
    CUSTOM(""); // 빈 문자열로 초기화된 커스텀 이모지

    private final String emoji;

    Emoji(String emoji) {
        this.emoji = emoji;
    }
}


Emoji customEmoji = Emoji.CUSTOM;
customEmoji.setEmoji("dpm"); // 예시로 디프만 사용자 지정 이모지를 추가
```

2023-12-14 11:11 UTC, CChuYong commented on post/src/main/java/com/oing/domain/model/MemberPostReaction.java
> +    private String emoji;
네 String인편이 나을 것 같아요 추가된다고 들었어서

2023-12-15 05:25 UTC, CChuYong approved these changes
수고하셨습니다!

2023-12-15 08:15 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +                    0, Collections.EMPTY_LIST, Collections.EMPTY_LIST));
네 맞아요~

2023-12-15 08:21 UTC, Kwon770 requested changes

2023-12-15 08:21 UTC, Kwon770 commented on post/src/main/java/com/oing/domain/model/MemberPost.java
> +    @Column(name = "content", columnDefinition = "VARCHAR(6)")
> 아하 넵. 코드에서 명시적으로 표시해주는 게 더 좋아보여서 그렇게 수정하겠습니다!

확장성을 위해 이렇게 디비 컬럼단에서 제약을 걸지말고, 코드 생성자에서 길이를 검증하는 코드를 추가하자는 뜻이였어요.

2023-12-15 08:21 UTC, Kwon770 commented
> 지난 회의 때 제가 질문한건데 생성자에 필요없는 리스트 컬럼은 제거하고 생성자를 사용하기로 해서 수정부탁드려요 🥺



> 네 맞아요~

이 부분 제가 답이 늦어서 반영이 안된거 같은데, 부탁드려요!

2023-12-15 09:12 UTC, Kwon770 approved these changes
확인했습니다. 수고하셨어요!

2023-12-15 09:12 UTC, merged