feat: Widget API 구현
depromeet/14th-team5-BE pull request #42
Opened 2023-12-15 17:25 UTC by Kwon770

## ❓ 기능 추가 배경

---
MVP 구현 범위인 단일 최근 가족 게시물 타입의 위젯을 위한 전용 API를 설계 및 구현했습니다. WidgetAPI와 WidgetController는 iOS 팀의 의견을 수용해 뷰에 맞춘 형태의 API로 설계합니다. 

## ➕ 추가/변경된 기능

---
- WidgetAPI, WidgetController 추가 (API Spec 설계)
- getSingleRecentFamilyPostWidget 요청 구현

## 🥺 리뷰어에게 하고싶은 말

---
Calendar API PR에서 구현한 비즈니스 코드들이 구현에 필수적이여서 `feature/OING-70` 브랜치를 머지했더니, PR 수정내역이 엉망징창이 되었네요.. 일단 급하게 구현 내용을 리뷰받기 위해서, PR로 생성했습니다. 이와 관련해서 따로 해결방안을 조언해주시면, 고쳐보겠습니다.

테스트 코드도 틈틈히 추가하겠습니다...

2023-12-16 03:41 UTC, CChuYong approved these changes
수고하셨습니다!

2023-12-16 03:41 UTC, CChuYong commented on post/src/main/java/com/oing/repository/MemberPostRepository.java
> +
이렇게 쿼리 날려야하는거면 가급적 쌩쿼리보단 쿼리DSL 쓰는게 좋을 것 같아요!

2023-12-16 03:55 UTC, Ji-soo708 requested changes
코멘트 한번만 확인해주세요! 수고하셨어요~

2023-12-16 03:55 UTC, Ji-soo708 commented on gateway/src/main/java/com/oing/restapi/WidgetApi.java
> +            @RequestParam(required = false)
저희 ResponseEntity 안쓰고 바로 DTO 넘기기로 했어요!

2023-12-17 14:36 UTC, Kwon770 commented on gateway/src/main/java/com/oing/restapi/WidgetApi.java
> +            @RequestParam(required = false)
@CChuYong  음.. 영민님이랑 이야기할 때 제가 이해하기로는 Response DTO만 보내되, 204처럼 나른 코드를 보내야한다면 ResponseEntiy를 쓴다고 이해했습니다. 본 요청은 게시글이 없을 때를 명확히 표현해야 한다고 생각해서, 204도 넣었습니다. 혹시 제가 이해한게 맞을까요?

2023-12-17 16:09 UTC, Ji-soo708 commented on gateway/src/main/java/com/oing/restapi/WidgetApi.java
> +            @RequestParam(required = false)
아 200번대 코드를 세부적으로 나누기로 했던 건 기억이 나네요. 일단 approve 남기겠습니다. 영민님도 맞다고 하면 머지하셔도 되세요! 수고하셨습니다~

2023-12-17 16:09 UTC, Ji-soo708 approved these changes

2023-12-18 03:30 UTC, Kwon770 commented
리뷰 사항을 전부 반영하였습니다. 시간상 테스트 코드까지 PR에 반영하기 힘들 것 같아, 변경사항을 확인하시고 바로 머지해주시면 감사하겠습니다!

* QueryDSL과 관련 리뷰사항이 #39 의 코드와 겹쳐서, feature/OING-70 브랜치에서 수정 후 이를 pull했습니다. 두 PR간에 겹치는 수정사항 때문에 계속 브랜치가 더러워지는데, 나중에 이에 관한 피드백을 요청드리고 싶네요. 😂

2023-12-18 03:40 UTC, CChuYong commented on gateway/src/main/java/com/oing/restapi/WidgetApi.java
> +            @RequestParam(required = false)
네 코드가 있으면 쓰기로 했었습니다!

2023-12-18 03:40 UTC, CChuYong approved these changes

2023-12-18 03:40 UTC, merged