[OING-80] feat: 멤버 정보 조회 관련 API 구현
depromeet/14th-team5-BE pull request #46
Opened 2023-12-19 10:01 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
멤버 조회와 관련된 가족 구성원 프로필 정보 조회 및 특정 회원 정보 조회 API를 구현했습니다.

## ➕ 추가/변경된 기능

---
- 가족 구성원 프로필 정보 조회
  - 프론트의 요청으로 가족 생성일도 함께 보냅니다 
  - 응답에서 해당 API를 요청한 회원의 정보가 먼저 위치합니다
- 특정 회원 정보 조회

## 🥺 리뷰어에게 하고싶은 말

---
리뷰 잘 부탁드립니다~

2023-12-19 10:02 UTC, Ji-soo708 commented on member/build.gradle
> +    implementation project(':family')
프로필 조회에서 가족 그룹 생성일을 보내려면 family 모듈의 의존성이 필요하여 추가했습니다.

2023-12-22 16:58 UTC, Kwon770 requested changes
전체적으로 스타일의 차이라 질문과 함께 LGTM드릴려 했으나, 마지막 MemberService 쪽 리뷰는 논의가 필요한 것 같아 Request changes 남깁니다!

2023-12-22 16:58 UTC, Kwon770 commented on family/src/main/java/com/oing/service/FamilyService.java
> +                .orElseThrow(FamilyNotFoundException::new);
family 엔티티에서 생성 시간을 뽑는 기능과 가족이 없으면 예외를 던지는, 성격이 다른 2가지 기능이 하나의 스트림에 묶여있는 것 같아요. 혹시 두 기능을 함수로 분리하는 건 어떨까요?

2023-12-22 16:58 UTC, Kwon770 commented on member/src/main/java/com/oing/restapi/MemberApi.java
> +    PaginationResponse<FamilyMemberProfileResponse> getFamilyMemberProfiles(
가족구성원들의 프로필들이니까, 혹시 `getFamilyMembersProfiles`는 어떨까요? 😀

2023-12-22 16:58 UTC, Kwon770 commented on member/src/main/java/com/oing/service/MemberService.java
> +    public Page<FamilyMemberProfileResponse> findFamilyProfilesByFamilyId(
엄연히 Member 모듈의 MemberService에서 가족구성원들의 프로필을 로드하는거니까, 명확히 `findFamilyMembersProfilesByFamilyId`가 좋은 것 같아요. (가족구성원 = family members)

2023-12-22 16:58 UTC, Kwon770 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .sorted(Comparator.comparing(profile -> userId.equals(profile.memberId()) ? 0 : 1))
이거 2가지 의문점이 있습니다.
1. @CChuYong 멤버나 피드 로드할 때, 유저 자신의 것은 가장 앞으로 오게 하는 정렬은 프론트에서 처리하도록 해야한다는 논의를 회의에서 들은 기억이 있는데, 서버에서 이렇게 구현해도 괜찮을까요?

2. [서버에서 구현한다면] 코드에서 이런 정렬의 코드에서(함수, 클래스, 등등) 의도를 알 수 없다고 느꼈습니다. 스트림으로 묶는 것이 아니라 별도로 분리하거나, 이 정렬의 의도를 함수애 표현해야 한다고 생각합니다.

2023-12-22 16:58 UTC, Kwon770 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .map(member -> new FamilyMemberProfileResponse(
mapping을 stream map 사용한 이유는 sorted를 사용하기 위함일까요? 개인적으로 mapping만을 위해 stream 사용은 지양해야 한다고 생각해서 질문드립니다,

2023-12-22 17:06 UTC, Ji-soo708 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .sorted(Comparator.comparing(profile -> userId.equals(profile.memberId()) ? 0 : 1))
1번에 대해서는 제가 영민님한테 저번에 여쭤봤는데 원래 그렇게 정렬이 안된 채로 주는 게 맞는데 유저 자신의 것은 맨 앞에 오도록 정렬해서 주자는 식으로 얘기가 마무리 되어서 저렇게 처리했습니다. rest하게 반환해야 한다면 바로 수정할게요~

2023-12-22 17:39 UTC, Ji-soo708 reviewed
순찬님이 남기신 코멘트 반영해서 코드 수정했습니다~ 가족 프로필 정보를 반환할 때 사용자의 프로필을 맨 앞에 오도록 정렬해서 줘야할지에 대한 부분은 내일 회의때 얘기 다시 한번 나눠보는 게 좋을 거 같아요!

2023-12-22 17:39 UTC, Ji-soo708 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .map(member -> new FamilyMemberProfileResponse(
응답을 반환할 때 사용자 자신의 프로필은 맨 앞에 위치시키기 위한  정렬과 매핑을 stream을 한 번에 처리할 수 있어 사용했습니다. 그런데 성능을 생각하면 해당 메서드에서는 굳이 stream을 쓸 필요는 없을 거 같습니다. 매핑 과정은 따로 for문으로 작성해서 수정할게요. 👍

2023-12-23 04:25 UTC, CChuYong commented on member/src/main/java/com/oing/service/MemberService.java
> +                .sorted(Comparator.comparing(profile -> userId.equals(profile.memberId()) ? 0 : 1))
정렬을 코드단에서 말고 쿼리단에서는 불가능할까용?

2023-12-23 05:43 UTC, Ji-soo708 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .sorted(Comparator.comparing(profile -> userId.equals(profile.memberId()) ? 0 : 1))
아까 얘기 나눴던대로 1차 MVP에서는 정렬을 빼겠습니다~

2023-12-23 07:08 UTC, CChuYong approved these changes

2023-12-23 11:16 UTC, Kwon770 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .map(member -> new FamilyMemberProfileResponse(
앗.. 제가 말을 잘못한 것 같아요. mapping library를 쓰거나 `...map(Dto::new).collection(...` 이렇게 작성하면 좋겠다는 리뷰를 할려고 했습니다. 😭 for문으로 작성하는 건 가독성이 너무 떨어지는 것 같아요. 😭 죄송함다

2023-12-23 11:18 UTC, Ji-soo708 commented on member/src/main/java/com/oing/service/MemberService.java
> +                .map(member -> new FamilyMemberProfileResponse(
아하 사실 저도 for문으로 쓰는 건 가독성때문에 지양하긴 하는데 해당 로직은 for문으로 작성해도 생각보다 간단해서 그 의도로 말씀하신 줄 알았네요 ㅎㅎ 해당 부분 반영하겠습니다~

2023-12-23 16:03 UTC, Kwon770 approved these changes
수고 많으셨어요!!

2023-12-23 16:03 UTC, merged