[OING-76] feat: post에 대한 반응 생성/삭제
depromeet/14th-team5-BE pull request #48
Opened 2023-12-19 12:45 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
< 여기에 기능 추가 배경 >

## ➕ 추가/변경된 기능

---
< 여기에 기능 >

## 🥺 리뷰어에게 하고싶은 말

---
< 여기에 하고싶은 말 >

2023-12-22 17:14 UTC, Kwon770 requested changes
수고하셧습니다! 확인부탁드려요 🙏

2023-12-22 17:14 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        addPostReaction(post, memberId, emoji);
validate를 별도의 함수로 빼고 핵심 로직인 addPostReaction을 이 함수 안에 적는건 어떻게 생각하세요? (아래 deletePostReaction도 마찬가지 피드백)

2023-12-22 17:14 UTC, Kwon770 commented on post/src/main/java/com/oing/service/PostReactionService.java
> +        }
늘 쓰는 find함수의 스트림 형태로 사용하는 것이 가능할 것 같아요! 

```
public MemberPost findMemberPostById(String postId) {
        return memberPostRepository
                .findById(postId)
                .orElseThrow(PostNotFoundException::new);
    }
```

2023-12-22 17:14 UTC, Kwon770 commented on post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
> +    Optional<MemberPostReaction> findReactionByPostIdAndMemberIdAndEmoji(String postId, String memberId, Emoji emoji);
위의 함수랑 MemberPost 파라미터 타입을 맞춰보는 건 어떨까요? 😀

2023-12-22 18:08 UTC, Kwon770 commented on post/src/main/java/com/oing/domain/model/MemberPostReaction.java
> +    @ManyToOne(fetch = FetchType.EAGER)
혹시 이건 왜 EAGER로 변경하신건가요?

2023-12-23 10:59 UTC, Ji-soo708 commented on post/src/main/java/com/oing/domain/model/MemberPostReaction.java
> +    @ManyToOne(fetch = FetchType.EAGER)
이전에 에러가 발생해서 고친다고 잠깐 수정해놓은 부분인데 확인을 못했네요.. 여기서는 LAZY로 하는 게 맞습니다! 체크해주셔서 감사해요 앞으로도 유의해서 볼게요~

2023-12-26 09:05 UTC, Kwon770 commented
LGTM 수고하셨어요~

2023-12-26 09:05 UTC, Kwon770 approved these changes
LGTM 수고하셨어요~

2023-12-26 09:05 UTC, merged