[OING-94] refactor: createPost 코드 개선 및 ZonedDateTime에서 LocalDate 추출 시 타임존 처리
depromeet/14th-team5-BE pull request #51
Opened 2023-12-22 16:00 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
영민님이 남기신 코멘트를 보고 리팩터링했습니다. 또한 ZonedDateTime에서 LocalDate 추출 시 +09:00 을 떼서 처리하기 때문에 새벽에 글을 올리면 이전 날로 등록되는 경우가 있습니다. 그래서 uploadDate 값을 구하기 위해 따로 코드에서 타임존 처리를 했습니다.

## ➕ 추가/변경된 기능

---
- createPost 코드 개선
- localDate 추출 시 타임존 처리

## 🥺 리뷰어에게 하고싶은 말

---
추가적으로 수정해야할 부분이 있다면 알려주세요~

2023-12-22 17:32 UTC, Kwon770 requested changes

2023-12-22 17:32 UTC, Kwon770 commented on common/src/main/java/com/oing/domain/exception/ErrorCode.java
> +    INVALID_UPLOAD_TIME("PO0001", "Invalid Upload Time"),
message는 클라이언트에게 노출되는 메시지이다보니까, 조금 더 자세하게 표현하는 것은 어떨까요? 시간 범위에 맞지 않는다는 점이 표현되면 좋을 것 같아요.

2023-12-22 17:32 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +        return new PostResponse(savedPost.getId(), savedPost.getMemberId(), 0, 0,
파리미터가 7개이므로, record에 of 함수를 만드는 것이 좋을 것 같습니다!

2023-12-22 17:32 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +        ZoneId serverTimeZone = ZoneId.of("Asia/Seoul");
이거는 ZonedLocalDateTime을 KST로 변경하는 코드로 보입니다. UTC로 통일해야하는 것 아닌가요?

2023-12-22 18:22 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostController.java
> +        ZoneId serverTimeZone = ZoneId.of("Asia/Seoul");
프론트에서 값을 줄 때는 KST로 받아와서 createdAt을 응답할 때도 KST로 답해야한다고 생각했고 API spec에서도 +09:00가 붙여져 있어 이렇게 구현했습니다. 다른 API들의 스웨거 api 스펙에도 ZonedDateTime으로 응답할 때 +09:00를 붙이는데 이건 내일 회의 때 얘기해봐요~

2023-12-26 09:09 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostController.java
> +        ZoneId serverTimeZone = ZoneId.of("Asia/Seoul");
클라이언트와 서버 비즈니스 코드, 서버 인프라 모두 KST로 통일하도록 합의했습니다.

2023-12-26 09:18 UTC, Kwon770 approved these changes
피드백드리고 합의한 내역들이 잘 반영되었네요! 수고하셨어요.

2023-12-26 09:19 UTC, merged