refactor: 게시물 반응 전체 조회 응답 형식 수정
depromeet/14th-team5-BE pull request #67
Opened 2024-01-03 10:08 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
프론트의 요청으로 게시물 반응 전체 조회 호출 시, 아래와 같이 응답이 가도록 수정했습니다.
```
{
    "emoji1MemberIds": [emoji1 누른 사용자 id들],
    "emoji2MemberIds": [emoji2 누른 사용자 id들],
    "emoji3MemberIds": [emoji3 누른 사용자 id들],
    "emoji4MemberIds": [emoji4 누른 사용자 id들],
    "emoji5MemberIds": [emoji5 누른 사용자 id들]
}

## ➕ 추가/변경된 기능

---
- 게시물 반응 전체 조회 응답 형식 수정

## 🥺 리뷰어에게 하고싶은 말

---
추가적으로 수정하면 좋은 부분이 있으면 알려주세요~

2024-01-03 10:16 UTC, Kwon770 requested changes
확인 부탁드려요!

2024-01-03 10:16 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +            List<String> emojiMemberIds = postReactionService.getMemberIdsByEmoji(postId, emoji);
내부 변수 처리를 위해 쿼리를 나누는 것을 올바르지 않다고 생각합니다. 글 개수 * 이모지 개수 만큼 쿼리가 나간다면, 앱 전체에서 봤을 때 너무 많은 쿼리가 나갈 것 같습니다. 한 번에 쿼리로 불로오고, 자바 선에서 분리하는 것은 어떨까요?

2024-01-03 10:16 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        for (Emoji emoji : EnumSet.of(Emoji.EMOJI_1, Emoji.EMOJI_2, Emoji.EMOJI_3, Emoji.EMOJI_4, Emoji.EMOJI_5)) {
이런 식으로 사용되는 케이스가 맞다면, emoji enum list를 관리하는 일급 객체를 따로 만드는 게 지금으로써도 코드가 깔끔해지고 혹시라도 이모지가 확장될 때 편할 것 같다고 생각했어요. 혹시 어떠실까요?

2024-01-03 10:29 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +            List<String> emojiMemberIds = postReactionService.getMemberIdsByEmoji(postId, emoji);
넵 성능 생각하면 순찬님 코멘트 따라가는 게 좋네요! 레포지토리 단에서는 한 번에 불러오고 자바 단에서 처리하겠습니다. 👍

2024-01-03 10:43 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        for (Emoji emoji : EnumSet.of(Emoji.EMOJI_1, Emoji.EMOJI_2, Emoji.EMOJI_3, Emoji.EMOJI_4, Emoji.EMOJI_5)) {
위에 남겨주신 코멘트 따라 수정해서 일급 객체를 따로 만들어 적용할 필요는 없다고 생각하여 생략했습니다. 나중에 이모지가 더 확장될 가능성이 있다면 그때는 일급 객체로 관리하도록 리팩터링해도 좋을 거 같아요~

2024-01-03 10:48 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        for (Emoji emoji : EnumSet.of(Emoji.EMOJI_1, Emoji.EMOJI_2, Emoji.EMOJI_3, Emoji.EMOJI_4, Emoji.EMOJI_5)) {
그럼 혹시 enum에 있는 이모지 한 번에 불러오는 방법 없나요? 이렇게 하나하나 지칭하는게 휴먼 에러의 여지가 너무 크다고 생각했습니다

2024-01-03 11:22 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        for (Emoji emoji : EnumSet.of(Emoji.EMOJI_1, Emoji.EMOJI_2, Emoji.EMOJI_3, Emoji.EMOJI_4, Emoji.EMOJI_5)) {
응답이 동적으로 변경되어야 하는데 시도해보니까 map을 이용해서 하면 가능합니다. 일단 제가 이해한 대로 수정해서 다시 푸쉬했습니다! 확인 부탁드려요~

2024-01-03 12:15 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        for (Emoji emoji : EnumSet.of(Emoji.EMOJI_1, Emoji.EMOJI_2, Emoji.EMOJI_3, Emoji.EMOJI_4, Emoji.EMOJI_5)) {
확인했습니다.

2024-01-03 12:16 UTC, Kwon770 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        emojiList.forEach(emoji -> emojiMemberIdsMap.putIfAbsent(emoji.getTypeKey(), Collections.emptyList()));
음.. 개인적으로 함수형과 stream이 복잡하게 사용되면서 가독성이 아쉽다고 생각하는데, 스타일의 차이일수도 있다고 생각되서 애매하네요. 🤔 @CChuYong 님도 검토해보시고 괜찮다고 생각하면 승인부탁드려요.

2024-01-03 13:00 UTC, Ji-soo708 commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        emojiList.forEach(emoji -> emojiMemberIdsMap.putIfAbsent(emoji.getTypeKey(), Collections.emptyList()));
저도 이 부분을 깔끔하게 작성하고 싶어서 여러 방식을 생각해봤는데 등록되지 않은 이모지까지 응답에 빈리스트로 포함되게 하려면 저 방식이 최선인 거 같더라고요. 더 좋은 방법이 있다면 코멘트 남겨주세요~

2024-01-04 01:28 UTC, CChuYong approved these changes

2024-01-04 01:28 UTC, CChuYong commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        emojiList.forEach(emoji -> emojiMemberIdsMap.putIfAbsent(emoji.getTypeKey(), Collections.emptyList()));
어떤 작업을 하는건지만 보이면 저는 함수형도 좋습니다~

2024-01-04 01:31 UTC, CChuYong reviewed
이제보니 API breaking 이네요.
응답 형태가 다른거면 경로가 v1/post/{}/reactions 는 그대로 두고 v1/post/{}/reactions/member (그냥 예시입니다) 같은 경로로 보내야할 것 같아요
v1/post/{}/reactions/{reactionId} 결과가 v1/post/{}/reactions 랑 다른게 약간 비약같습니다!

2024-01-04 01:32 UTC, CChuYong requested changes
이제보니 API breaking 이네요.
응답 형태가 다른거면 경로가 v1/post/{}/reactions 는 그대로 두고 v1/post/{}/reactions/member (그냥 예시입니다) 같은 경로로 보내야할 것 같아요
v1/post/{}/reactions/{reactionId} 결과가 v1/post/{}/reactions 랑 다른게 약간 비약같습니다!

2024-01-04 01:33 UTC, CChuYong commented on post/src/main/java/com/oing/controller/PostReactionController.java
> +        emojiList.forEach(emoji -> emojiMemberIdsMap.putIfAbsent(emoji.getTypeKey(), Collections.emptyList()));
함수형은 저도 상관은 없습니다 해당 코드가 무슨 일을 하는지만 잘 보인다면 ㅎㅎㅎ

2024-01-04 08:32 UTC, CChuYong approved these changes

2024-01-04 08:43 UTC, Kwon770 approved these changes

2024-01-04 08:43 UTC, merged