[OING-10] chore: 프로젝트에 Jacoco 설정
depromeet/14th-team5-BE pull request #7
Opened 2023-11-23 11:11 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
code coverage를 측정하기 위해 프로젝트에 Jacoco를 도입했습니다. 해당 PR이 merge된 후에 SonarQube(SonarCloud)를 세팅할 예정입니다.

## ➕ 추가/변경된 기능

---
- 프로젝트에 Jacoco 도입

## 🥺 리뷰어에게 하고싶은 말

---
리뷰 잘부탁드립니다 ☺️

## 🔗 참조 or 관련된 이슈

---
https://no5ing.atlassian.net/browse/OING-10

2023-11-23 11:14 UTC, Ji-soo708 commented on build.gradle
> +			csv.required.set(true)
`html.enabled true` 이런 식으로 많이 쓰던데 deprecated 되었다해서 `html.required.set(true)`로 작성했습니다.

2023-11-23 11:14 UTC, Ji-soo708 commented on build.gradle
> -}
subProjects 안으로 옮겼습니다.

2023-11-23 11:36 UTC, CChuYong approved these changes
수고하셨습니다! 혹시 jacoco test는 어떻게 동작시키는건가요? ./gradlew jacoco 이런식으로 실행하는건가요?

2023-11-23 11:37 UTC, CChuYong requested changes
앗 이제 확인해보니 PR 브랜치 타겟이 main이네요! feature -> dev -> release -> main 이라서 dev로 잡아주시면 감사하겠습니다

2023-11-23 12:35 UTC, Ji-soo708 commented
> 수고하셨습니다! 혹시 jacoco test는 어떻게 동작시키는건가요? ./gradlew jacoco 이런식으로 실행하는건가요?

 ./gradlew --console verbose test
하면 `test -> jacocoTestReport -> jacocoTestCoverageVerification` 이 자동으로 수행됩니다. 그런데 제가 방금 코드 일정 부분을 잘못된 위치에 작성된 걸 확인해서 다시 push했습니다. pull 받고 한 번 확인해주세요! 현재 PR에서 test코드가 `ServerApplication`만 있는데 `ServerApplication`은 자코코 테스트 범위에서 제외해서 Application 관련 패턴을 주석처리 하면 결과 확인하실 수 있을거에요!

2023-11-24 00:54 UTC, CChuYong approved these changes
확인했습니다! 수고하셨습니다!

2023-11-24 03:04 UTC, merged