test: 회원 정보수정/조회/탈퇴에 대한 단위 테스트 코드 추가
depromeet/14th-team5-BE pull request #89
Opened 2024-01-09 09:11 UTC by Ji-soo708

## ❓ 기능 추가 배경

---
제가 구현한 회원 정보수정(프로필이미지, 닉네임), 회원 정보조회(멤버, 가족멤버), 탈퇴에 대해 단위 테스트 코드를 추가했습니다.

## ➕ 추가/변경된 기능

---
- 회원 정보수정 단위테스트 코드 추가
- 회원 정보조회 단위테스트 코드 추가
- 회원 정보탈퇴 단위테스트 코드 추가

## 🥺 리뷰어에게 하고싶은 말

---
이런 방식으로 단위 테스트 코드를 작성한 건 처음인데 잘못 작성한 부분이 있는지 리뷰 부탁드립니다~ 
현재 테스트 코드 기준으로 커버리지 100 채웠습니다.
<img width="973" alt="스크린샷 2024-01-09 오후 6 08 10" src="https://github.com/depromeet/14th-team5-BE/assets/69844138/7df9e091-4c2c-4b24-a42d-2cef2f27b8c3">

2024-01-13 08:27 UTC, CChuYong approved these changes
LGTM 수고하셨습니다!

2024-01-13 12:19 UTC, Kwon770 requested changes
코드리뷰와 특정 테스트코드 사용법에 대한 질문 남겼습니다! 확인부탁드려요.

2024-01-13 12:19 UTC, Kwon770 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +                LocalDate.of(2003, 7, 26), "testMember2", null, null);
@BeforeEach는 모든 테스트 마다 실행되는 것이므로, 단순히 하드코딩된 객체를 생성하는 것을 여기서 할 필요는 없다고 생각해요. 필드 선언하는 곳에서 바로 넣어도 될 것 같습니다!

2024-01-13 12:19 UTC, Kwon770 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +        Member member = spy(TEST_MEMBER1);
특별히 spy로 한 이유가 있을까요? Member필드는 모킹한 함수의 결과값으로 사용하기 위한 용도로 보이는데, 그냥 자바 객체를 리턴값에 할당해도 되는 것으로 알고 있습니다!

2024-01-13 12:19 UTC, Kwon770 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +        verify(member).updateName(eq(newName));
verify를 처음봐서 조금 알아봤는데, 모킹한 객체의 동작을 검증하기 위한 것으로 이해했습니다. 테스트코드 흐름상 약간 이해가 안가서 질문드립니다! 다른 verify 사용처에도 마찬가지 질문입니다!

1. Member는 모킹되지 않아서 verify의 사용이 올바른게 맞을까요?
2. 통합테스트가 아니라 단위테스트인데, 메서드의 동작이 제대로 이루어졌는지를 검증할 필요가 있을까요? 네트워크가 연관되지 않은 순수 java 코드가 제대로 작동되었는지를 검증하는 것으로 보여서 질문드립니다!

2024-01-13 12:35 UTC, Ji-soo708 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +        Member member = spy(TEST_MEMBER1);
spy말고 memberService 통해 회원 생성을 시도하면 제대로 생성되지 않아 테스트를 진행할 수 없습니다. 해결방법 찾다가 spy로도 모킹하여 테스트할 수 있다하여 해당 방법 사용했습니다.

2024-01-13 12:41 UTC, Ji-soo708 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +        verify(member).updateName(eq(newName));
테스트코드 안에서 verify를 쓰는 곳도 있고 안쓰는 곳도 존재하는데 해당 파일 안에서는 verify 검증문은 다 없애는 게 맞네요.👍🏻

2024-01-14 04:58 UTC, Ji-soo708 commented on member/src/test/java/com/oing/controller/MemberControllerTest.java
> +        Member member = spy(TEST_MEMBER1);
spy 제외하고 바로 멤버 객체 할당하도록 수정했습니다!

2024-01-14 06:27 UTC, Kwon770 approved these changes
수정사항 다 확인했습니다 LGTM!

2024-01-14 06:28 UTC, merged